sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t dinesh98/react-test -f ./client/Dockerfile.dev .
script:
    - docker run -e CI=true  dinesh98/react-test npm run test -- --coverage


after_success:
    - docker build -t dinesh98/multi-client ./client
    - docker build -t dinesh98/multi-nginx  ./nginx
    - docker build -t dinesh98/multi-server ./server
    - docekr build -t dinesh98/multi-worker ./worker
    # Login in to the Docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --PASSWORD-stdin  
    # Take those images and push them to Docker hub
    - docker push dinesh98/multi-client
    - docker push dinesh98/multi-nginx
    - docker push dinesh98/multi-server
    - docker push dinesh98/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-546792522289"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
